import Link from "next/link";

import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Mario Kart Scoreboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <header>Mario Kart Scoreboard</header>
        <nav>
          <Link href="/">Scoreboard</Link>
          <Link href="/seasons">Seasons</Link>
          <Link href="/tournaments">Tournaments</Link>
          <Link href="/players">Players</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
