import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  SignInButton,
} from "@clerk/nextjs";
import "~/styles/globals.css";
import NavigationBar from "~/components/NavigationBar";
import { User as UserIcon } from "~/components/Icons";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Mario Kart Scoreboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="antialiased">
          <header className="underline-wavy decoration-3 flex w-full flex-row items-center justify-between bg-[#E52521] p-3 text-center font-mario text-xl text-white shadow sm:p-6 sm:text-4xl md:text-left">
            Mario Kart Scoreboard
            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <SignInButton>
                <button>
                  <UserIcon />
                </button>
              </SignInButton>
            </SignedOut>
          </header>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none bg-[#E52521]/65 md:w-48 md:p-6 md:shadow">
              <NavigationBar />
            </div>
            <div className="flex flex-grow p-6 md:overflow-y-auto md:p-8">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
